# Generated by Django 6.1.1 on 2026-09-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do aluno.', max_length=255)),
                ('idade', models.PositiveSmallIntegerField(help_text='Idade do aluno.')),
                ('escola', models.CharField(help_text='Instituição de origem do aluno.', max_length=255)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
    ]
