# Generated by Django 6.1.1 on 2026-09-24 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(help_text='Uma das 12 disciplinas do I Ciclo.', max_length=100)),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota do aluno na disciplina (10-20).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)])),
                ('aluno', models.ForeignKey(help_text='Aluno a quem esta nota pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Nota de Disciplina',
                'verbose_name_plural': 'Notas de Disciplina',
                'ordering': ['aluno', 'disciplina'],
                'unique_together': {('aluno', 'disciplina')},
            },
        ),
    ]
