# Generated by Django 6.1.1 on 2026-09-30 09:04

import alunos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_notadisciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='codigo_acesso',
            field=models.CharField(default=alunos.models.gerar_codigo_acesso, editable=False, help_text='Código gerado automaticamente para o aluno voltar ao seu perfil.', max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='solicitacoes_orientacao',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de vezes que o motor de recomendação já foi accionado (máximo 3).'),
        ),
    ]
