# Generated by Django 6.1.1 on 2026-10-02 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_notadisciplina"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="criado_em",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data e hora em que o aluno iniciou o teste.",
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="tentativa_cat",
            field=models.PositiveSmallIntegerField(
                default=1,
                editable=False,
                help_text="Tentativa actual do CAT (1 ou 2). A 2.ª só existe se a 1.ª tiver confiança baixa e o aluno aceitar repetir.",
            ),
        ),
    ]
