# Generated by Django 6.1.1 on 2026-09-24 11:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do curso técnico.', max_length=255)),
                ('instituicao', models.CharField(help_text='ITEL, IPIL, IMEL, IMS ou CEARTE.', max_length=100)),
                ('arquetipo_dominante', models.CharField(choices=[('Analítico', 'Analítico'), ('Humanista', 'Humanista'), ('Criativo', 'Criativo'), ('Estrategista', 'Estrategista')], help_text='Analítico, Humanista, Criativo ou Estrategista.', max_length=20)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PreRequisitoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(help_text='Disciplina de pré-requisito.', max_length=100)),
                ('nota_min', models.PositiveSmallIntegerField(help_text='Nota mínima exigida (10-20).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)])),
                ('curso', models.ForeignKey(help_text='Curso a que este pré-requisito pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisitos', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Pré-requisito de Curso',
                'verbose_name_plural': 'Pré-requisitos de Curso',
                'unique_together': {('curso', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='VetorIdealCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(help_text='Disciplina.', max_length=100)),
                ('peso_ideal', models.PositiveSmallIntegerField(help_text='Valor de referência validado por peritos (10-20).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)])),
                ('curso', models.ForeignKey(help_text='Curso a que este vetor pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='vetores_ideais', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Vetor Ideal do Curso',
                'verbose_name_plural': 'Vetores Ideais do Curso',
                'unique_together': {('curso', 'disciplina')},
            },
        ),
    ]
