# Generated by Django 6.1.1 on 2026-09-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Enunciado da questão.')),
                ('tipo', models.CharField(choices=[('nucleo', 'Núcleo'), ('verificacao', 'Verificação de Coerência')], default='nucleo', help_text='Núcleo ou verificação de coerência (RF05).', max_length=20)),
                ('opcoes', models.JSONField(help_text='Lista de 4 opções. Ex: [{"texto": "...", "arquetipo": "Analítico"}, ...]')),
            ],
            options={
                'verbose_name': 'Item CAT',
                'verbose_name_plural': 'Itens CAT',
            },
        ),
    ]
