# Generated by Django 6.1.1 on 2026-09-24 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_notadisciplina'),
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaCAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquetipo_escolhido', models.CharField(choices=[('Analítico', 'Analítico'), ('Humanista', 'Humanista'), ('Criativo', 'Criativo'), ('Estrategista', 'Estrategista')], help_text='Arquétipo associado à opção escolhida pelo aluno.', max_length=20)),
                ('aluno', models.ForeignKey(help_text='Aluno que respondeu.', on_delete=django.db.models.deletion.CASCADE, related_name='respostas_cat', to='alunos.aluno')),
                ('item', models.ForeignKey(help_text='Item CAT respondido.', on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='cat.itemcat')),
            ],
            options={
                'verbose_name': 'Resposta CAT',
                'verbose_name_plural': 'Respostas CAT',
                'unique_together': {('aluno', 'item')},
            },
        ),
    ]
