# Generated by Django 6.1.1 on 2026-10-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat", "0002_respostacat"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcat",
            name="tendencia",
            field=models.CharField(
                choices=[
                    ("neutra", "Neutra"),
                    ("Analítico", "Analítico"),
                    ("Humanista", "Humanista"),
                    ("Criativo", "Criativo"),
                    ("Estrategista", "Estrategista"),
                ],
                default="neutra",
                help_text="Arquétipo para o qual a situação da pergunta puxa naturalmente (a opção desse arquétipo é a mais 'socialmente esperada'). Usado na calibração do CAT adaptativo.",
                max_length=20,
            ),
        ),
    ]
