# Generated by Django 6.1.1 on 2026-10-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat", "0003_itemcat_tendencia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemcat",
            options={
                "ordering": ["posicao", "id"],
                "verbose_name": "Item CAT",
                "verbose_name_plural": "Itens CAT",
            },
        ),
        migrations.AddField(
            model_name="itemcat",
            name="ativo",
            field=models.BooleanField(
                default=True,
                help_text="Só os itens activos entram no CAT. Desactivar em vez de apagar preserva as respostas antigas.",
            ),
        ),
        migrations.AddField(
            model_name="itemcat",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Código do item no banco validado (ex.: AN-01). Opcional para itens novos.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="itemcat",
            name="contexto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Escola", "Escola"),
                    ("Família", "Família"),
                    ("Bairro", "Bairro"),
                    ("Amigos", "Amigos"),
                ],
                help_text="Contexto da situação (escola, família, bairro, amigos).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itemcat",
            name="par_coerencia",
            field=models.CharField(
                blank=True,
                help_text="Identificador do par de coerência (ex.: P1). Os dois membros do par medem a mesma preferência em contextos diferentes.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="itemcat",
            name="posicao",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Ordem de referência na versão fixa do teste (1 a 20).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemcat",
            name="opcoes",
            field=models.JSONField(
                help_text='Lista de 4 opções, uma por arquétipo. Ex: [{"texto": "...", "arquetipo": "Analítico", "faceta": "Física", "peso": 1.0}, ...]'
            ),
        ),
    ]
