# Generated by Django 6.1.1 on 2026-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0003_aluno_criado_em_aluno_tentativa_cat"),
        ("cat", "0004_itemcat_banco_v2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="respostacat",
            options={
                "ordering": ["aluno", "tentativa", "respondida_em", "id"],
                "verbose_name": "Resposta CAT",
                "verbose_name_plural": "Respostas CAT",
            },
        ),
        migrations.AddField(
            model_name="respostacat",
            name="posicao_ecra",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                help_text="Posição da opção escolhida no ecrã (as opções são baralhadas).",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="respostacat",
            name="respondida_em",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="respostacat",
            name="tempo_resposta_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tempo que o aluno levou a responder, em milissegundos (enviado pelo frontend).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="respostacat",
            name="tentativa",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Tentativa do CAT a que esta resposta pertence. As respostas de tentativas anteriores ficam guardadas para análise.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="respostacat",
            unique_together={("aluno", "item", "tentativa")},
        ),
    ]
