# Generated by Django 6.1.1 on 2026-09-24 11:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_notadisciplina'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_academico', models.FloatField(help_text='Similaridade de Cosseno calculada (RF08).')),
                ('score_psicografico', models.FloatField(help_text='Afinidade com o arquétipo dominante.')),
                ('score_final', models.FloatField(help_text='Combinação ponderada dos dois scores.')),
                ('rank', models.PositiveSmallIntegerField(help_text='Posição no ranking final (1 a 3).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('escolhida_pelo_aluno', models.BooleanField(default=False, help_text='Indica se esta foi a recomendação seleccionada pelo aluno (RF13).')),
                ('aluno', models.ForeignKey(help_text='Aluno a quem esta recomendação pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='alunos.aluno')),
                ('curso', models.ForeignKey(help_text='Curso recomendado.', on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'ordering': ['aluno', 'rank'],
                'unique_together': {('aluno', 'rank')},
            },
        ),
    ]
