# Generated by Django 6.1.1 on 2026-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='alertas_vieses',
            field=models.JSONField(blank=True, default=dict, help_text='Alertas de viés detectados (RF09, RF11). Ex: {"sobrestimacao": ["Analítico"], "subestimacao": []}'),
        ),
    ]
