# Generated by Django 6.1.1 on 2026-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recomendacoes", "0002_recomendacao_alertas_vieses"),
    ]

    operations = [
        migrations.AddField(
            model_name="recomendacao",
            name="confianca_cat",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Qualidade das respostas ao CAT quando a recomendação foi gerada. Ex: {"nivel": "baixa", "motivos": ["..."]}. O orientador vê este rótulo.',
            ),
        ),
    ]
